django-authen/authen/authen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
]

django-authen/authen/login/urls.py
from django.urls import path
from .views import LoginClass, ViewUser, view_product, AddPost

app_name = 'Login'
urlpatterns = [
    path('', LoginClass.as_view(), name="login"),
    path('user-view/', ViewUser.as_view(), name="user_view"),
    path('view-product/', view_product, name="view-product"),
    path('add-post/', AddPost.as_view(), name="add_post"),
]

django-authen/authen/login/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=255)

    def __str__(self):
        return self.title

django-authen/authen/login/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

django-authen/authen/login/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm

# Create your views here.

class LoginClass(View):
    def get(self, req):
        return render(req, "login/login.html")

    def post(self, req):
        username = req.POST.get('username')
        password = req.POST.get('password')
        my_user = authenticate(username=username, password=password)
        if my_user is None:
            return HttpResponse("Sai ten dang nhap hoac mat khau")

        login(req, my_user)
        return render(req, 'login/success.html')

class ViewUser(LoginRequiredMixin, View):
    login_url = '/login/'
    def get(self, req):
        return HttpResponse('<h1>Day la View User(Ban da dang nhap)</h1>')

@decorators.login_required(login_url='/login/')
def view_product(req):
    return HttpResponse('Xem san pham')


class AddPost(LoginRequiredMixin, View):
    login_url = '/login/'
    def get(self, req):
        f = PostForm()
        context = {'fm': f}
        return render(req, 'login/add_post.html', context)

    def post(self, req):
        f = PostForm(req.POST)
        if f.is_valid():
            if req.user.has_perm('Login.add_post'):
                f.save()
            else:
                return HttpResponse('Permission Deny!')
        else:
            return HttpResponse('Form Invalid!')
        return HttpResponse('oke')

django-authen/authen/login/templates/login/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'Login:add_post' %}" method="post">
        {% csrf_token %}
        {{ fm }}
        <input type="submit" value="ADD">
    </form>
</body>
</html>

django-authen/authen/login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <div class="login">
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="username"/>
            <input type="password" name="password"/>
            <input type="submit" value="Login"/>
        </form>
    </div>
</body>
</html>

django-authen/authen/login/templates/login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .message {
            color: dodgerblue;
        }
    </style>
</head>
<body>
    <div class="message">
        <h3>Đăng nhập thành công</h3>
    </div>
</body>
</html>