learn-django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

learn-django/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name="index"),
    path('list/', views.showAllQuestions, name='view_list'),
    path('abc/', views.ham1, name="ham"),
    path('detail/<int:question_id>/', views.detailView, name="detail"),
    path('<int:question_id>', views.submit, name="vote")
]

learn-django/mysite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

learn-django/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question

# Create your views here.

# function base view
def index(request):
    my_name = "HungNN"
    taisan = ["Dien thoai", "May tinh", "May bay"]
    return render(request, "polls/index.html", {"name": my_name, "taisan": taisan})

def ham1(req):
    return HttpResponse("<h1>Ham linh tinh</h1>")

def showAllQuestions(req):
    list_question = Question.objects.all()
    context = {"questions": list_question}
    return render(req, "polls/questions.html", context)

def showOneQuestion(req):
    question = get_object_or_404(Question, pk=1)
    return render(req, "polls/questions.html", {"question": question})


def detailView(req, question_id):
    question = Question.objects.get(pk=question_id)
    return render(req, "polls/detail_question.html", {"question": question})

def submit(req, question_id):
    q = Question.objects.get(pk=question_id)
    try:
        data = req.POST['choice']
        c = q.choice_set.get(pk=data)
    except:
        HttpResponse("NO CHOICE")
    c.vote = c.vote + 1
    c.save()
    return render(req, "polls/result.html", {"question": q})

learn-django/mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div class="header">
        <h1>My website by Django</h1>
    </div>
    <div class="menu">
        <ul>
            <li>Link 1</li>
            <li>Link 2</li>
            <li>Link 3</li>
            <li>Link 4</li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="content">
        {% block contentQuestion %}
        {% endblock %}
    </div>
    <div class="content">
        {% block detailQuestion %}
        {% endblock %}
    </div>
</body>
</html>

learn-django/mysite/polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{% block detailQuestion %}
    {% if question %}
    <h3>{{ question.question_text }}</h3>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <ul>
            {% for item in question.choice_set.all %}
            <div class="d-flex">
                <li><input type="radio" value="{{ item.id }}" name="choice">{{ item.choice_text }}</li>
            </div>
            {% endfor %}
            <p><input type="submit" value="Submit"></p>
        </ul>
    </form>
    {% endif %}
{% endblock %}

learn-django/mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>Day la template</h1>
    <p>Chao the gioi, Toi ten la {{ name }}</p>


<h2>Tai san toi co:</h2>
<ul>
    {% for  item in taisan %}
        {% if item != 'May tinh' %}
        <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}

learn-django/mysite/polls/templates/polls/questions.html
{% extends 'polls/base.html' %}

{% block contentQuestion %}
    {% if questions %}
    <ul>
        {% for item in questions %}
        <div class="d-flex">
            <a href="{% url 'polls:detail' item.id %}"><li>{{ item.question_text }}</li></a>
        </div>
        {% endfor %}
    </ul>
    {% else %}
        <h2>Khong co du lieu</h2>
    {% endif %}

    <h3>Day la 1 cau hoi:</h3>
    <p>{{ question.question_text }}</p>
{% endblock %}

learn-django/mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content %}

    {% if question %}
        <h3>{{ question.question_text }}</h3>
        <p>Ket qua binh chon la</p>
        {% for item in question.choice_set.all %}
            <p>{{ item.choice_text }} : {{ item.vote }}</p>
        {% endfor %}
        <a href="{% url 'polls:view_list' %}">Vote tiep</a>
    {% endif %}

{% endblock %}