form-django/demoForm/demoForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

form-django/demoForm/news/urls.py
from django.urls import path
from . import views

app_name= 'news'
urlpatterns = [
    path('', views.index, name="index"),
    # path('add/', views.addPost, name="addPost"),
    path('save/', views.SavePost.as_view(), name="save"),
    path('email/', views.emailView, name="email"),
    path('receivedEmail/', views.receivedEmail, name="receivedEmail"),
    path('views/', views.IndexClass.as_view(), name="views"),
]

form-django/demoForm/news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000, blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

    def __str__(self):
        return self.title

form-django/demoForm/news/forms.py
from django import forms
from . models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'time_create',)
        widgets = {
            'title': forms.TextInput({'class': 'title'}),
            'content': forms.Textarea({'class': 'content'})
        }


class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'title'}))
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class': ''}))
    cc = forms.BooleanField(required=False)

form-django/demoForm/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm, SendEmail
from django.views import View

# Create your views here.

def index(req):
    return HttpResponse('Chao')

def addPost(req):
    f = PostForm()
    return render(req, "news/add_new.html", {"f": f})

def saveNew(req):
    if req.method == 'POST':
        data = PostForm(req.POST)
        if data.is_valid():
            data.save()
            return HttpResponse('Luu thanh cong')
        else:
            return HttpResponse('Luu that bai, du lieu khong hop le')
    else:
        return HttpResponse('Bad request 400')

def emailView(req):
    f = SendEmail()
    return render(req, 'news/email.html', {'f': f})

def receivedEmail(req):
    if req.method == 'POST':
        mailForm = SendEmail(req.POST)
        if mailForm.is_valid():
            title = mailForm.cleaned_data['title']
            content = mailForm.cleaned_data['content']
            email = mailForm.cleaned_data['email']
            cc = mailForm.cleaned_data['cc']
            context = {"title": title, 'cc': cc, "content": content, "email": email}
            context2 = {"f": mailForm}
            # mailForm.save()
            return render(req, "news/print_email.html", context2)
        else:
            return HttpResponse('Luu that bai, du lieu khong hop le')
    else:
        return HttpResponse('Bad request 400')

# class  base view
class IndexClass(View):
    def get(self, req):
        return HttpResponse("This is class base view")


class SavePost(View):
    def get(self, req):
        f = PostForm()
        return render(req, "news/add_new.html", {"f": f})

    def post(self, req):
        f = PostForm(req.POST)
        if f.is_valid():
            f.save()
            return HttpResponse("Luu thanh cong")
        else:
            return HttpResponse("Invalid!")

form-django/demoForm/news/templates/news/add_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="post">
        {% csrf_token %}
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>
        <p>{{ f.time_create }}</p>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

form-django/demoForm/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email</title>
</head>
<body>
    <form action="{% url 'news:receivedEmail' %}" method="post">
        {% csrf_token %}
        <p>Title</p><p>{{ f.title }}</p>
        <p>Email</p><p>{{ f.email }}</p>
        <p>Content</p><p>{{ f.content }}</p>
        <p>CC</p><p>{{ f.cc }}</p>
        <input type="submit" value="Gửi email">
    </form>
</body>
</html>

form-django/demoForm/news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <table>
        <tr>
            <td>Tiêu đề</td>
            <td>Nội dung</td>
            <td>Email</td>
            <td>CC</td>
        </tr>
        <tr>
            <td>{{ f.title }}</td>
            <td>{{ f.content }}</td>
            <td>{{ f.email }}</td>
            <td>{{ f.cc }}</td>
        </tr>
    </table>
</body>
</html>